### PR TITLE
Fixed sending messages in dms; Added package.json; Simplified `checkIfEmpty`

### PR DESCRIPTION
**Pull request by 13-05**

### CODE REVIEW

**Review by paintingofblue — APPROVED** [review]
thank you, i've been busy so i haven't been able to work on this

**Comment by 13-05** [comment]
all good! i'll see if i can tackle some of the things on your "todo" section asw.

**Comment by paintingofblue** [comment]
apologies if some of this is a little hard to read, i'm new to js

**Comment by 13-05** [comment]
that's fine haha, i might reformat some stuff but this is a really nice project! i've tried some stuff like this but i always feel like the ui part is soooo painful, so i just give up

**Pull request merged**
